### ISSUE TITLE
Network section greyed out and says Not Supported

### ISSUE THREAD

**Issue by jstma** [mirfatif/MyLocation#2]
I'm guessing that network location is showing "Not Supported" because I have google play services disabled on a "de-googled" stock Android 11.  I'm suffering without location tagging photos or navigation, but I can't just install LineageOS on this phone (yet).

The readme.md says "On the devices with Google Play Services installed, NLP usually uses Google Location Service at backend."  I installed an NLP backend, but that didn't help.

Due to the word "usually", I'm hoping there's a way to use network location without Google Location Service.  And then it's a question of whether or not this app can provide network location to other apps.

**Comment by mirfatif** [comment]
> I'm guessing that network location is showing "Not Supported" because I have google play services disabled

You guessed correctly.

>  I installed an NLP backend, but that didn't help.  
...  
Due to the word "usually", I'm hoping there's a way to use network location without Google Location Service

NLP Backend alone is of no use. Install UnifiedNLP (or microG GmsCore) which can make use of NLP backends to get location. UnifiedNLP is a location provider; an open-source alternative to proprietary Play Services.

But this is irrelevant to My Location.

>  And then it's a question of whether or not this app can provide network location to other apps.

My Location? No. This app is a location consumer, not a location provider. It just shows the location information received from AOSP location providers (GPS and Network) or directly from UnifiedNLP Backends (whichever is available on the device).

**Comment by jstma** [comment]
Seems I misunderstood what this app was capable of doing.  My bad and thanks for clearing that up.

No root means no UnifiedNLP, is that correct?

**Comment by mirfatif** [comment]
> No root means no UnifiedNLP, is that correct?

Yes. You can check their documentation, it's quite comprehensive: https://github.com/microg/UnifiedNlp
